### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by lgl1227** [mattharmer/Fish-Identifier-Model#2]
![image](https://user-images.githubusercontent.com/55053750/80341412-f8448980-8894-11ea-95fb-c79730418181.png)
![image](https://user-images.githubusercontent.com/55053750/80341423-00042e00-8895-11ea-9100-b84bda10b343.png)

**Comment by mattharmer** [comment]
Check out the tfhub for correct URL. https://tfhub.dev/s?subtype=module,placeholder
